name: eh
description: 嗯了
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  queue: ^3.1.0+1
  scraper: 
    git: https://github.com/xioxin/scraper.git
    # path: ../scraper
  dio: ^4.0.0
  dio_domain_fronting: 
    path: ./package/dio_domain_fronting
  json_annotation: ^4.1.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: 3.0.1
  loggy: ^2.0.1
  args: ^2.0.0
  objectdb: ^1.2.1+1
  pretty_dio_logger: ^1.2.0-beta-1
  dio_smart_retry: ^1.1.0
  rxdart: ^0.27.3
  characters: ^1.2.0
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
